### ISSUE TITLE
Add `Position` class

### ISSUE THREAD

**Issue by TonyTroeff** [SiT-Academy-Students/Labyrinth#2]
In our source code we have a few places where we use variables `x` and `y` to denote a position.
Let's extract a class for this purpose.

![image](https://user-images.githubusercontent.com/33567383/228924224-ed147721-e718-4d77-bc34-572046579280.png)
![image](https://user-images.githubusercontent.com/33567383/228924623-f40dd663-f43d-4b1f-aeae-49513c7de88c.png)

**Comment by goshoch08** [comment]
Added a new coordinates class and replaced every x and y variable with the class contents (PS I forgot how to pull request)
![image](https://user-images.githubusercontent.com/120674338/233132129-6d91d6fa-85e8-41fe-83a9-cc3f073634a4.png)
![image](https://user-images.githubusercontent.com/120674338/233132220-3ad0722f-4c21-4a87-9f80-2c2b94335610.png)
![image](https://user-images.githubusercontent.com/120674338/233132428-192a1ed1-55b3-4926-94f0-b9f83aeb9949.png)
![image](https://user-images.githubusercontent.com/120674338/233132490-8dceb3c1-ff6d-4598-a0f4-9189a4124bda.png)
![image](https://user-images.githubusercontent.com/120674338/233132611-a8b048f4-bffa-4010-a41c-122f955d998e.png)
![image](https://user-images.githubusercontent.com/120674338/233132700-002f7d58-f0fe-40b0-9c5f-938036a34839.png)
